### PR TITLE
#166816124 Super admin create users

### PR DESCRIPTION
**Pull request by dharmykoya**
#### What does this PR do?
Allow super admin create users
#### Description of Task to be completed?
- To write Test for all the functions
- To add validations to the user model
- To create a super admin seed file
- To allow super admin create users
- To allow super admin and admin update, users
- To allow super admin and admin delete users
- To install husky
#### How should this be manually tested?
N/A
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[166816124](https://www.pivotaltracker.com/story/show/166816124)
#### Screenshots (if appropriate)
N/A
#### Questions:
N/A

### CODE REVIEW

**Review by devPinheiro — APPROVED** [review]
Good job! I would like you to fix the failing build on Travis.

**Comment by fxola** [comment]
Nice work dammy. Just like Sam said, look into your failing build please

**Comment by dharmykoya** [comment]
> Good job! I would like you to fix your failing build on Travis.

Done already

**Comment by dharmykoya** [comment]
> Nice work dammy. Just like Sam said, look into your failing build please

done that already, thanks

**Pull request closed without merging**
