### PR TITLE
 #166816101 User can sign out

### PR DESCRIPTION
**Pull request by tunedev**
#### What does this PR do?
It adds Endpoint GET: /users/logout

#### Any background context you want to provide?
NA

#### What are the relevant pivotal tracker stories?
The pivotal [#166816101](https://www.pivotaltracker.com/story/show/166816101)

#### Screenshots (if appropriate)
NA

#### Questions:
NA

### CODE REVIEW

**Comment by dharmykoya** [comment]
Looks good to me.... you can edit the title of the PR as well.

**Comment by tunedev** [comment]
> Looks good to me.... you can edit the title of the PR as well.

Thanks, @dharmykoya for pointing that out

**Comment by fxola** [comment]
LGTM

**Review by devPinheiro — COMMENTED** [review]
LGTM

**Comment by halimahO** [comment]
LGTM

**Pull request merged**
