### PR TITLE
#166816090 configure eslint

### PR DESCRIPTION
**Pull request by tunedev**
#### What does this PR do?
Configures eslint and prettier

#### How should this be manually tested?
NA

#### What are the relevant pivotal tracker stories?
[#166816090](https://www.pivotaltracker.com/story/show/166816090)

#### Screenshots (if appropriate)
NA
#### Questions:
NA

### CODE REVIEW

**Review by devPinheiro — CHANGES_REQUESTED** [review]
Hi, you have done a great job here. Kindly follow the convention for PR naming. Remove the ':' in the PR title. Thanks

**Comment by tunedev** [comment]
> Hi, you have done a great job here. Kindly follow the convention for PR naming. Remove the ':' in the PR title. Thanks

Thanks, @devPinheiro, Change has been made.

**Comment by dharmykoya** [comment]
LGTM... good one Tunde

**Review by devPinheiro — APPROVED** [review]

**Comment by halimahO** [comment]
LGTM

**Comment by halimahO** [comment]
LGTM

**Review by devPinheiro — APPROVED** [review]
LGTM

**Pull request merged**
